name: cn_younglee_pomodoro
description: "番茄时间"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.2
  fl_chart: 0.66.2
  intl: ^0.20.2
  table_calendar: ^3.2.0
  sqflite: ^2.3.2
  timezone: ^0.10.0
  image_picker: ^1.0.7
  # 添加通知相关依赖
  flutter_local_notifications: ^18.0.1
  # 添加音频播放依赖
  just_audio: ^0.9.36
  # 添加震动相关依赖
  vibration: ^3.1.3
  # 添加应用内权限请求
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/sounds/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FF7F5F"
  remove_alpha_ios: true 